/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java2lab5s2;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author yunusemreadas
 */
public class q1 extends javax.swing.JFrame {
    ArrayList<String> list = new ArrayList<String>();
    DefaultListModel lst_resultModel;

    /**
     * Creates new form q1
     */
    public q1() {
        initComponents();
        list.add("Yunus Adaş");
         list.add("Ali Adaş");
          list.add("Cihan Adaş");
           list.add("Mustafa Adaş");
           lst_resultModel= new DefaultListModel();
           lst_result.setModel(lst_resultModel);
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        btngr_1 = new javax.swing.ButtonGroup();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txt_search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_result = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel4 = new javax.swing.JPanel();
        rdbtn1 = new javax.swing.JRadioButton();
        rdbtn2 = new javax.swing.JRadioButton();
        rdbtn3 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        chcbx_1 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtarea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        jPanel1.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 46, 270, 30));

        jLabel1.setText("SEARCH");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 64, -1));

        jLabel2.setText("RESULT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        jScrollPane1.setViewportView(lst_result);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 330, 210));

        jTabbedPane3.addTab("Search", jPanel1);
        jPanel1.getAccessibleContext().setAccessibleName("tab_search");

        jPanel2.setBackground(new java.awt.Color(0, 51, 255));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jSplitPane1.setBackground(new java.awt.Color(255, 102, 102));
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setMinimumSize(new java.awt.Dimension(247, 300));
        jSplitPane1.setPreferredSize(new java.awt.Dimension(350, 300));

        jPanel4.setBackground(new java.awt.Color(255, 102, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Search"));
        jPanel4.setMinimumSize(new java.awt.Dimension(400, 310));
        jPanel4.setPreferredSize(new java.awt.Dimension(346, 300));

        btngr_1.add(rdbtn1);
        rdbtn1.setSelected(true);
        rdbtn1.setText("Start With");
        rdbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtn1ActionPerformed(evt);
            }
        });

        btngr_1.add(rdbtn2);
        rdbtn2.setText("Contain");

        btngr_1.add(rdbtn3);
        rdbtn3.setText("End With");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rdbtn1)
                    .addComponent(rdbtn2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbtn3, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(rdbtn1)
                .addGap(26, 26, 26)
                .addComponent(rdbtn2)
                .addGap(26, 26, 26)
                .addComponent(rdbtn3)
                .addGap(125, 125, 125))
        );

        jSplitPane1.setTopComponent(jPanel4);

        jPanel5.setBackground(new java.awt.Color(102, 51, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Result"));
        jPanel5.setMinimumSize(new java.awt.Dimension(346, 200));
        jPanel5.setPreferredSize(new java.awt.Dimension(346, 200));
        jPanel5.setRequestFocusEnabled(false);

        chcbx_1.setText("Delete With Right Click");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(chcbx_1)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chcbx_1)
                .addGap(99, 99, 99))
        );

        jSplitPane1.setRightComponent(jPanel5);

        jPanel2.add(jSplitPane1);

        jTabbedPane3.addTab("Setings", jPanel2);
        jPanel2.getAccessibleContext().setAccessibleName("tab_settings");

        jPanel3.setBackground(new java.awt.Color(204, 255, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtarea.setColumns(20);
        txtarea.setLineWrap(true);
        txtarea.setRows(5);
        txtarea.setText("asdkjasjdsakjdnlsalkdlasdlasldlaskdlasdlnasdnlsad");
        jScrollPane2.setViewportView(txtarea);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 16, 290, 410));

        jTabbedPane3.addTab("About", jPanel3);
        jPanel3.getAccessibleContext().setAccessibleName("tab_about");

        getContentPane().add(jTabbedPane3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtn1ActionPerformed

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
         String text = txt_search.getText();
        for(String item:list){
            if(rdbtn1.isSelected()){
                if(item.startsWith(text)){
                    lst_resultModel.addElement(item);
                }else if (rdbtn2.isSelected()){
                    if(item.contains(text)){
                        lst_resultModel.addElement(item);
                    }
                }else {
                    if(item.endsWith(text)){
                        lst_resultModel.addElement(item);
                    }
                }
                
            }
            
        }
    }//GEN-LAST:event_txt_searchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(q1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(q1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(q1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(q1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new q1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngr_1;
    private javax.swing.JCheckBox chcbx_1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JList<String> lst_result;
    private javax.swing.JRadioButton rdbtn1;
    private javax.swing.JRadioButton rdbtn2;
    private javax.swing.JRadioButton rdbtn3;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextArea txtarea;
    // End of variables declaration//GEN-END:variables
}
